/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import member.UserDAO;
/**
 *
 * @author User
 */
public class srchForm extends javax.swing.JFrame {

    /**
     * Creates new form srchForm
     */
    public srchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmail2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSrchID = new javax.swing.JLabel();
        lblPasswd = new javax.swing.JLabel();
        btnID = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnPasswd = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("srchInfo");

        jPanel1.setBackground(new java.awt.Color(194, 217, 241));

        lblEmail2.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblEmail2.setText("이메일");

        lblEmail.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblEmail.setText("이메일");

        lblSrchID.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblSrchID.setText("* 아이디 찾기 *");

        lblPasswd.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblPasswd.setText("* 비밀번호 찾기 *");

        btnID.setBackground(new java.awt.Color(255, 255, 204));
        btnID.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        btnID.setText("아이디 찾기");
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        btnPasswd.setBackground(new java.awt.Color(255, 255, 204));
        btnPasswd.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        btnPasswd.setText("비밀번호 찾기");
        btnPasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswdActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblID.setText("아이디");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEmail)
                            .addGap(399, 399, 399)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblSrchID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail2)
                            .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnPasswd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblPasswd)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblSrchID)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnID)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lblPasswd)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail2)
                    .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPasswd))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed

        String email = txtEmail.getText().trim();

        if(email.equals("")){
            JOptionPane.showMessageDialog(null, "이메일을 입력해주세요.");
        }else if ((txtEmail.getText().length() < 4) || !txtEmail.getText().contains("@") || !txtEmail.getText().contains(".")) { //이메일 형식 확인
            JOptionPane.showMessageDialog(null, "잘못된 이메일 형식입니다.");
            txtEmail.setText(null);
        }else{
            UserDAO userDAO = new UserDAO();
            String srchID = userDAO.srchUserID(txtEmail.getText());

            if(srchID == null){//아이디 찾기 실패
                JOptionPane.showMessageDialog(null, "등록된 아이디가 없습니다.");
                txtEmail.setText(null);
            }else{
                JOptionPane.showMessageDialog(null, "아이디는 " + srchID + "입니다");
                txtEmail.setText(null);
            }
        }
    }//GEN-LAST:event_btnIDActionPerformed

    private void btnPasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswdActionPerformed

        String id = txtID.getText();
        String email = txtEmail2.getText();

        if(id.equals(""))
        JOptionPane.showMessageDialog(null, "아이디를 입력해주세요.");
        else if(email.equals(""))
        JOptionPane.showMessageDialog(null, "이메일을 입력해주세요.");
        else if ((txtEmail2.getText().length() < 4) || !txtEmail2.getText().contains("@") || !txtEmail2.getText().contains(".")) { //이메일 형식 확인
            JOptionPane.showMessageDialog(null, "잘못된 이메일 형식입니다.");
            txtEmail2.setText(null);
        }else {
            UserDAO userDAO = new UserDAO();
            String srchPasswd = userDAO.srchUserPasswd(txtID.getText(), txtEmail2.getText());

            if(srchPasswd == null){//비밀번호 찾기 실패
                JOptionPane.showMessageDialog(null, "등록된 비밀번호가 없습니다.");
                txtID.setText(null);
                txtEmail2.setText(null);
            }else{
                JOptionPane.showMessageDialog(null, "비밀번호는 " + srchPasswd + "입니다");
                txtID.setText(null);
                txtEmail2.setText(null);
            }
        }
    }//GEN-LAST:event_btnPasswdActionPerformed

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
    
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(srchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new srchForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnPasswd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblSrchID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
